[profile.default]
solc-version = "0.8.22"
verbosity = 2
optimizer = true
optimizer_runs = 31137
# true for stack-too-deep error avoidance,
# off for speedy builds (if it compiles)
via_ir = true
test = 'tests/sol/unit'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
cache_path = 'forge-cache'
no_match_test = 'testSkip'
fs_permissions = [{ access = "read", path = "./scripts/config"}]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.invariant]
runs = 25

[profile.integration]
test = 'tests/sol/integration'

[profile.gas]
test = 'tests/sol/gas'