name: Slither
"on":
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    slither:
        runs-on: ubuntu-latest
        env:
            INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
        permissions:
            contents: read
            security-events: write
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Use env file
              uses: c-py/action-dotenv-to-setenv@v2
              with:
                  env-file: .env.example
            - name: Run Slither
              uses: crytic/slither-action@v0.1.0
              continue-on-error: true
              id: slither
              with:
                  target: contracts/
