---
name: Tests
"on":
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install Node.js
              uses: actions/setup-node@v3
            - name: Use env file
              uses: c-py/action-dotenv-to-setenv@v2
              with:
                  env-file: .env.example
            - name: Install the Node.js dependencies
              run: npm ci
            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly
            - name: Show the Foundry config
              run: forge config
            - name: Run the tests
              run: npm run test
            - name: Add test summary
              run: |
                  echo "## Tests" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
